baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My Hugo Blog'
theme = 'tailwind-theme'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[taxonomies]
  tag = "tags"
  category = "categories"
