baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'CodePromptFu Blog'
theme = 'tailwind-theme'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menus]
  [[menus.main]]
    name = "CodePromptFu"
    url = "https://www.codepromptfu.com"
    weight = 1
  [[menus.main]]
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  [params.author]
    url = "https://x.com/debamitro"
    name = "@debamitro"
