baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'CodePromptFu Blog'
theme = 'tailwind-theme'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = "CodePromptFu Home"
    url = "https://www.codepromptfu.com"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
  tag = "tags"
  category = "categories"
